Revert V8 commit which broke our Windows build
With this new V8 commit, our Windows build broke with the following
error:

    external/v8/src/heap/base/asm/x64/push_registers_asm.cc(24,2): error: "The masm based version must be used for Windows"